steps:
- name: "gcr.io/cloud-builders/docker"
  args:
  - build
  - "--tag=gcr.io/$mental-health-app-479702/python-image"
  - "--file=./.cloud/Dockerfile"
  - .

images:
- "gcr.io/$mental-health-app-479702/python-image"
