# Generated by Django 5.1.2 on 2025-02-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("password_hash", models.CharField()),
                ("password_salt", models.CharField()),
                ("kdf_salt", models.CharField()),
                ("creation_date", models.DateTimeField()),
            ],
        ),
    ]
