# Generated by Django 5.1.2 on 2025-02-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(max_length=64),
        ),
        migrations.AlterField(
            model_name="account",
            name="kdf_salt",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
