# Generated by Django 5.1.2 on 2025-02-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="password_salt",
        ),
        migrations.AlterField(
            model_name="session",
            name="token",
            field=models.CharField(max_length=86),
        ),
    ]
