version: '3.8'

services:
  emulator:
    build:
      dockerfile: Dockerfile.android
    environment:
      EMULATOR_DEVICE: "Nexus 4"
      WEB_VNC: true
      WEB_LOG: true
      EMULATOR_NO_SKIN: true
      EMULATOR_ADDITIONAL_ARGS: "-no-snapshot -camera-back none -camera-front none -accel on -no-boot-anim -no-audio"
    devices:
      - /dev/kvm
    # Persisting data may cause issues:
    # https://github.com/budtmo/docker-android/issues/439
    # volumes:
    #   - emulator-data:/home/androidusr
    
    network_mode: service:app

volumes:
  # emulator-data:
